### ISSUE TITLE
TechReborn (1.12.2-2.26.3.1066) - crashing during startup

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn-Legacy-Issues#26]
**Describe the bug**
Mod crashing during startup after upgrading to the newest version of TR and RC

**Environment**
 - Minecraft: 1.12.2
 - Mod Loader: forge 14.23.5.2847

**Logs**
https://paste.dimdev.org/ixuqobolif.mccrash

**Additional context**
 And yes, I have enabled Deduplication with mod IC2 Classic

**Comment by drcrazy** [comment]
Duplicate for #15 
Already fixed in dev. Release will be in 1-2 days.

**Comment by SanityCh3ck** [comment]
Still getting the exact same crash with IC2 Classic.

**Environment**
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Tech Reborn: 2.27.2.1079
- IC2 Classic: 1.5.4.5

**Crash report**
https://paste.dimdev.org/gukiludeku.mccrash
