### ISSUE TITLE
Machines facing wrong position when loading save again

### ISSUE THREAD

**Issue by LegendLZD** [TechReborn/TechReborn-Legacy-Issues#27]
I used electric furnace for example
I have placed 6 electric furnaces which were facing me
![2020-01-30_10 30 44](https://user-images.githubusercontent.com/44722752/73415161-fe85a100-434b-11ea-900b-00ed124e4b7b.png)
But when I loaded save again,electric furnaces were not facing me
![2020-01-30_10 31 14](https://user-images.githubusercontent.com/44722752/73415286-5f14de00-434c-11ea-8556-4364665b857b.png)
They were facing another position instead,and they looked like working,but in fact it didn't have anything in each electric furnace,and didn't have any generators connected them
![2020-01-30_10 31 22](https://user-images.githubusercontent.com/44722752/73415320-705dea80-434c-11ea-82cb-30545ed2ba8b.png)
I'm not sure whether it is a bug in TR latest version.If it is a bug,please fix it thx:)
TR Version: TechReborn-1.12.2-2.27.0.1072-universal
RC Version: RebornCore-1.12.2-3.19.0.516-universal

**Comment by thearistocrats** [comment]
I'm having this same problem too
RebornCore-1.12.2-3.19.0.516-universal
TechReborn-1.12.2-2.27.0.1072-universal
wrenching them doesn't always fix it, the multi-block machines don't register their machine
forge 1.12.2

**Comment by LegendLZD** [comment]
A probably method to solve this problem is facing machines to north or south,facing machines to west or east will cause this bug

**Comment by drcrazy** [comment]
I hope I will have time to check this issue over weekend. @oOLegendOo  Thanks for workaround

**Comment by modmuss50** [comment]
Reverted the change, and removed the build that contained this broking change.
