### ISSUE TITLE
1.12.2 Missing recipe

### ISSUE THREAD

**Issue by Neuromantix** [TechReborn/TechReborn-Legacy-Issues#33]
Missing recipe: 4 small iron dust to 1 iron dust
Version 1.12.2

**Comment by modmuss50** [comment]
<img width="1792" alt="Screenshot 2020-03-05 at 19 21 36" src="https://user-images.githubusercontent.com/4324090/76017465-8f850480-5f16-11ea-8f88-4d22601b0f24.png">

Looks fine to me
