### ISSUE TITLE
Cables won't connect to MV transformer multi-dot side after updating

### ISSUE THREAD

**Issue by viveleroi** [TechReborn/TechReborn-Legacy-Issues#37]
**Describe the bug**
After updating to the latest release of TechReborn/RebornCore, no cables will connect to the "multi dot" side of an MV transformer. I've tried rotating and re-placing the transformer and cables.

I also tried using different cables, in case I mixed up which was input vs output. Gold cables won't connect either.

I also lost some machine rotations and my industrial grinder vanished entirely, but this is the only issue so far I can't fix.

**Steps to Reproduce**
- Install latest version of mod
- Place MV transformer. Cables won't connect to multi-dot side using default config.

**Screenshots**
https://i.imgur.com/ASmqXTv.png

**Environment (please complete the following information with the version):**
 - Minecraft: 1.12.2
 - Mod Loader:  forge-14.23.5.2847
 - TechReborn-1.12.2-2.27.1.1076-universal
 - RebornCore-1.12.2-3.19.2.522-universal

**Logs**
N/A

**Additional context**
N/A

**Comment by drcrazy** [comment]
Can't reproduce in dev env. Can you update to latest RC & TR (TechReborn-1.12.2-2.27.2.1079) and retest, please?

![image](https://user-images.githubusercontent.com/1382352/82909314-c8f76a00-9f71-11ea-91b9-1f442b474dac.png)
