### ISSUE TITLE
[1.12.2] Electric Furnace drop Basic Machine Frame when incorrect break

### ISSUE THREAD

**Issue by DArkHekRoMaNT** [TechReborn/TechReborn-Legacy-Issues#38]
Electric Furnace drop Basic Machine Frame when you break it by pickaxe. But it is crafting from Iron Furnace and not use Basic Machine Frame.

Minecraft 1.12.2
TechReborn 2.27.1.1076

**Comment by drcrazy** [comment]
Yeah, no frame in crafting recipe for electric furnace. On the other hand:
Basic machine frame  = 8 refined iron  = 8 iron ingots
Electric furnace = 5 iron ingots, 1 refined iron ingot, some cables, redstone, etc. 

Still a loss of resources if broken by pickaxe.

**Comment by DArkHekRoMaNT** [comment]
Only if the recipe of the basic machine frame is not changed

**Comment by drcrazy** [comment]
Then recipe for Electric Furnace could be also changed to have basic frame in it. For example, replace iron furnace in recipe with machine frame.
