### ISSUE TITLE
Recipe Problem

### ISSUE THREAD

**Issue by Dylanc6981** [TechReborn/TechReborn-Legacy-Issues#39]
Recipe In jei isnt working for hv transformer, and looked it up on google and tried it and it still doesnt work. In pack World of dragons By Kreezxil

**Comment by drcrazy** [comment]
Can't reproduce in dev env. Please, report to pack author. 

![image](https://user-images.githubusercontent.com/1382352/82908630-ed9f1200-9f70-11ea-82a3-2a149c4162fd.png)
