### ISSUE TITLE
All machines are missing textures when placed facing upwards.

### ISSUE THREAD

**Issue by Kenja-mc** [TechReborn/TechReborn-Legacy-Issues#40]
**Describe the bug**
Machines are missing textures when placed in the **up** orientation.

**Steps to Reproduce**
- Select a few machines and place them about 2 or 3 blocks away from you.
  - These machines have normal textures
  - Press F3 and see they are oriented in the direction you placed them.
- Place the blocks again, this time below the player, or one block next to the player
  - These machines will have the missing Pink and Black textures
  - Press F3 and see they are looking in the **up** orientation.

**Screenshots**
![](https://user-images.githubusercontent.com/18564584/80414069-0f37ab80-8896-11ea-9d48-fb23e29ee79f.png)
![](https://i.imgur.com/FhhZ1df.png)

TechReborn 2.27.1.1076 and Reborn Core 3.19.2.522, which is one release version behind the latest one, does not have this issue:
![image](https://user-images.githubusercontent.com/18564584/80656479-eefb1e80-8a46-11ea-8ddd-c8303a82a0a0.png)

All that has to be done is add textures for this orientation, or rollback the code that added directional machine textures in the latest version.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.12.2
 - Mod Loader: Forge 14.23.5.2854
 - TechReborn-1.12.2-2.27.2.1079-universal.jar
 - RebornCore-1.12.2-3.19.3.524-universal.jar

**Logs**
tbh I don't think they're helpful in this case
See attached:
[latest.log](https://github.com/TechReborn/TechReborn/files/4488452/latest.log)

**Comment by Kenja-mc** [comment]
OK so I just got back to developing my modpack with Tech Reborn in it, and it seems this is actually a problem that affects all machine textures.

As you can see there is no texture whenever a machine is placed in the "up" direction.

I will update the issue title accordingly

![image](https://user-images.githubusercontent.com/18564584/80414069-0f37ab80-8896-11ea-9d48-fb23e29ee79f.png)

**Comment by lakotajames** [comment]
Any idea what version I have to go back to, to avoid this?

**Comment by Kenja-mc** [comment]
I tested [TechReborn 2.27.1.1076](https://www.curseforge.com/minecraft/mc-mods/techreborn/files/2894949) and [Reborn Core 3.19.2.522](https://www.curseforge.com/minecraft/mc-mods/reborncore/files/2898260), which is one release version behind for both mods. This was done in forge-14.23.5.2854.

As you can see in the image below, there is no texture error:
![2020-04-29_18 15 43](https://user-images.githubusercontent.com/18564584/80655934-82335480-8a45-11ea-9236-aed6ae820242.png)
Notice that in the image, the machine is facing **north**, rather than **up**. So the problem is that there is no texture for the **up** direction. 

@lakotajames
I haven't tested it, but I'm sure you could make a resource pack and just copy the textures for the up and down directions and rotate them if you want. Otherwise you can just use the previous versions that I listed above, which can be downloaded using the Twitch app or the links I posted.

**Comment by lakotajames** [comment]
Ah.  I had tried downgrading TechReborn, but forgot to also try Core.  Thanks!

**Comment by SPglouglou** [comment]
this texture bug is also present for all block with face down.

**Comment by drcrazy** [comment]
Fixed in RC
