### ISSUE TITLE
I can't get the energy out of the fusion control computer

### ISSUE THREAD

**Issue by teillet86** [TechReborn/TechReborn-Legacy-Issues#46]
Issue:
    Power (EU and Fe) extraction from tech reborn fusion reactors.

 - Minecraft: all the mods 3 remix 1.12.2

I can't get more than 32,768 rf / t out of the fusion control computer when it produces 61mrf / t
I tried the thermal cryo cable the techreborn superconductor cable
is there a solution

**Comment by drcrazy** [comment]
```
Fusion Control Computer will provide energy from top and bottom sides and will accept energy from other sides. 
```

Are you trying to get it from above mentioned sides?

**Comment by teillet86** [comment]
yes i try a bunch of stuff but i found nothing

**Comment by teillet86** [comment]
yes i try a bunch of stuff but i found nothing

**Comment by drcrazy** [comment]
75kRF/t - easily. 

Check what is i\o rate for power accepting tile

![image](https://user-images.githubusercontent.com/1382352/82947306-7dac7e00-9fa8-11ea-956a-631344c3ee9a.png)

**Comment by teillet86** [comment]
I did the same setup as on the photo and there is only 32768 rf / t
![2020-05-27_16 48 54](https://user-images.githubusercontent.com/65628872/83036563-0b38ae00-a03b-11ea-9343-40fa87c17da3.png)
I did the same setup as on the photo and there is only 32768 rf / t
would it come from the modpack?

**Comment by drcrazy** [comment]
There will be RC & TR release soon. Let's wait for it and retest.

**Comment by teillet86** [comment]
after doing tests on ftb continuum it is true that it works I go out more 32768 I will see with the devs of the modpack
do you know we could change this?

**Comment by teillet86** [comment]
it's good i found the solution it's in the config files you have to deactivate the support of the ic2 power supply and i can finally get my 61mrf / t
